---
- name: Run front
  community.docker.docker_container:
    name: front
    image: "{{ dockerhub_user }}/tp-devops-front:latest"
    pull: always
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network }}"
